// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvwkcpcawgzdvqdfkeop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2d2tjcGNhd2d6ZHZxZGZrZW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODY0MjgsImV4cCI6MjA2NjI2MjQyOH0.AoKOYF_xF_dWCjuuEl-XEMmx0c22VUYrfF2ne94gr5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);